server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: servicio-student
        uri: http://localhost:8010/
        predicates:
        - Path=/api/student/**
      - id: service-FamilyRelative
        uri: http://localhost:8020/
        predicates:
        - Path=/api/familyRelative/**
        
      - id: service-teacher
        uri: http://localhost:8030/
        predicates:
        - Path=/api/teacher/**
